# Generated by Django 4.2.8 on 2024-01-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommapp", "0004_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="qty",
            field=models.ImageField(default=1, upload_to=""),
        ),
    ]
