# Generated by Django 4.2.8 on 2024-01-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommapp", "0007_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amt",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
